#!/bin/bash
dir=$PWD
frps=/usr/local/frps
frps_script=/etc/init.d/frps

#自己定义修改参数
####################################################################
#监听端口
bind_port=9170
#认证口令
token=pjk
#kcp监听端口
kcp_bind_port=9170
#udp监听端口
bind_udp_port=9171
#web面板监听端口
dashboard_port=7500
#web面板用户名和密码
dashboard_user=jk
dashboard_pwd=19960915
#日志文件处理
log_file=/usr/local/frps/frps.log
log_level=error
log_max_days=2
###################################################################


frps_menu ()
{
   echo "############1.安装frps###########"
   echo "############2.卸载frps###########"
}
frps_start ()
{
read input
case "$input" in

1 )
    pid=`ps -ef | grep -v grep | grep -i $frps | awk '{print $2}'`
    if [ "$pid" ]; then
    echo "frps is already installed!" && exit 0
    fi
    if [ ! -w ${dir}/frps.tar.gz ];then
    wget -N --no-check-certificate https://github.com/liubei66/remote_frps/raw/master/frps.tar.gz
    fi
    tar -xvf ${dir}/frps.tar.gz 2>&1 &
    sleep 1
    echo `mv -f "${dir}/frps1/" "$frps"`
    sleep 1
    echo `mv -f "${dir}/frps" "$frps_script"`
    #配置文件修改
    sed -i "/^bind_port/cbind_port = ${bind_port}" ${frps}/frps.ini
    sed -i "/^token/ctoken = ${token}" ${frps}/frps.ini
    sed -i "/^kcp_bind_port/ckcp_bind_port = ${kcp_bind_port}" ${frps}/frps.ini
    sed -i "/^bind_udp_port/cbind_udp_port = ${bind_udp_port}" ${frps}/frps.ini
    sed -i "/^dashboard_port/cdashboard_port = ${dashboard_port}" ${frps}/frps.ini
    sed -i "/^dashboard_user/cdashboard_user = ${dashboard_user}" ${frps}/frps.ini
    sed -i "/^dashboard_pwd/cdashboard_pwd = ${dashboard_pwd}" ${frps}/frps.ini
    sed -i "/^log_file/clog_file = ${log_file}" ${frps}/frps.ini
    sed -i "/^log_level/clog_level = ${log_level}" ${frps}/frps.ini
    sed -i "/^log_max_days/clog_max_days = ${log_max_days}" ${frps}/frps.ini

    chkconfig frps on && service frps start
    pid=`ps -ef | grep -v grep | grep -i $frps | awk '{print $2}'`
    if [ "$pid" ]; then
    echo "install success!" && exit 0
    fi
    echo "install fail!"
    exit 0
    ;;
2 )
    pid=`ps -ef | grep -v grep | grep -i $frps | awk '{print $2}'`
    if [ "$pid" ]; then
    kill -9 "$pid" && echo "stop frps..........."
    fi
    if [ -x "$frps_script" ] ; then
    chkconfig frps off && rm -f $frp_script
    fi
    rm -rf $frps && echo "uninstall frps success!"
    exit 0
    ;;
*)
    echo "输入错误，请重试"
    ;;
    esac
}
for((i=1;i<=3;i++)) ; 
do
frps_menu;
frps_start;
done
echo "尝试超过三次，程序退出！"
exit 0
