#!/bin/bash
dir=$PWD
menu ()
{
  echo "#########################"
  echo "安装常用脚本自定义脚本工具"
  echo "#########################"
  echo "1.安装/卸载frps"
  echo "0.退出"
}
start ()
{
read input
case "$input" in

1 )
    if [ ! -w ${dir}/install_frps ];then
    wget -N --no-check-certificate https://github.com/liubei66/remote_frps/raw/master/install_frps && chmod +x install_frps && bash install_frps
    fi
    chmod +x install_frps && bash install_frps
    break
    ;;
* )
   echo "输入错误，请重试！"
   ;;
0 )
    exit 0
    ;;
    esac
}
while [ 1 ] ; do
menu
start
done
